export enum TAG {
  auth = "@auth",
  notAuthorized = "@notAuthorized",
  authorized = "@authorized",
  roleRead = "@roleRead",
  roleWrite = "@roleWrite",
  roleAdmin = "@roleAdmin",
  course = "@course",
  regression = "@regression",
  positive = "@positive",
  negative = "@negative",
  passToken = "@passToken",
  clientToken = "@clientToken",
  aiGenerated = "@aiGenerated",
}
